version: 0.2

env:
  variables:
    REPO_URL: https://github.com/Yasir-Tariq121/demo-repo.git
    REPO_BRANCH: main
  git-credential-helper: yes

phases:
  build:
    commands:
      - sh build-wrapper.sh $REPO_URL $REPO_BRANCH # These environment variables come from the CFN stack
      - git log | head -100