- name: Validate Services
  hosts: all

  tasks:
    - name: Check connection to google
      uri:
        url: "{{ google_url }}"
        method: GET
      register: _result_jenkins
      until: _result_jenkins.status == 200
      retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
      delay: 5 # Every 5 seconds
