version: 2.1
jobs:
  Run-CDK:
    docker:
      - image: nikolaik/python-nodejs:python3.8-nodejs12-alpine
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Install dependencies
          command: |
            npm install -g aws-cdk@1.118.0
            cdk --version
            pip install -r requirements.txt
      - run:
          name: Set Virtual ENV and run Pip requirements
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
      # - run:
      #     name: Install Pip Requirements
      #     command: |
      #       pip install -r requirements.txt
      # - run:
      #     name: CDK Synthesize
      #     command: |
      #       npm install -g aws-cdk@1.118.0
      #       cdk --version

workflows: 
  version: 2
  run_cdk:
    jobs:
      - Run-CDK:
          filters:
            branches:
              only: main
          # context: stage
      # - Deployment:
      #     requires:
      #       - Build-and-Push-Stage
      #     filters:
      #       branches:
      #         only: master
      #     context: stage