version: 2.1
jobs:
  build:
    docker:
      - image: docker:18.09.3-git
    working_directory: /tmp
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo this is a test
      - when:
          condition:
            on_fail
          steps:
            - run: echo this is a failed step
workflows:
  sample:
    jobs:
      - build
