version: 2.1
parameters:
  environment:
    type: string
    default: test-env # from circleci context
  stack:
    type: string
    default: test-stack
jobs:
  Job1:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: test step
          command: |
            echo test step
      

workflows: 
  version: 2
  run_cdk_dev:
    jobs:
      - Job1:
          filters:
            branches:
              only: main
          context: dev
          post-step:
            - run:
                command: echo "this is a post step"