#branch feature
version: 2.1
parameters:
  environment:
    type: string
    default: test-env # from circleci context 
  stack:
    type: string
    default: test-stack
jobs:
  bar:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: test step
          no_output_timeout: 10s
          command: |
            echo test step
            sleep 30m
      - run:
          name: commands on fail
          command: echo this is failing......
          # when: on_fail
      
workflows:
  build:
    jobs:
      - bar:
          filters:
            branches:
              only: main
          context: test
#           post-steps: # steps to run after steps defined in the job bar **
#             - run:
#                 name: Kick off new pipeline
#                 command: |
#                   COMMIT_ID=$(git rev-parse --short HEAD)
#                   curl -u ${API_TOKEN}: -X POST --header "Content-Type: application/json" -d '{
#                     "parameters": {
#                       "platform_branch": "${CIRCLE_BRANCH}",
#                       "platform_commit": "'"$COMMIT_ID"'",
#                       "platform_environment": "tests"
#                     }
#                   }' https://circleci.com/api/v2/project/github/Yasir-Tariq121/demo/pipeline
#                   echo this is another pipeline trigger step
# workflows: 
#   version: 2
#   run_cdk_dev:
#     jobs:
#       - Job1:
#           filters:
#             branches:
#               only: main
#           context: dev
#           post-step:
#             - run:
#                 command: echo "this is a post step"

# curl --location --request POST 'https://circleci.com/api/v2/project/github/Yasir-Tariq121/demo/pipeline' \
#                   --header 'Content-Type: application/x-www-form-urlencoded' \
#                   -u "${API_TOKEN}"
