version: 2.1
jobs:
  build:
    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo this is a test
      - when:
          condition:
            on_fail
          steps:
            - failure:
                name: Failure step
                command: echo this is a failed step
workflows:
  sample:
    jobs:
      - build
