version: 2.1
parameters:
  environment:
    type: string
    default: test-env # from circleci context
  stack:
    type: string
    default: test-stack
jobs:
  bar:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: test step
          command: |
            echo test step
      
workflows:
  build:
    jobs:
      - bar:
          filters:
            branches:
              only: main
          context: test
          post-steps: # steps to run after steps defined in the job bar
            - run:
                name: Kick off new pipeline
                command: |
                  curl --location --request POST 'https://circleci.com/api/v2/project/github/Yasir-Tariq121/demo/pipeline', 'branch_name:${CIRCLE_BRANCH}' \
                  --header 'Content-Type: application/json' \
                  -u "${API_TOKEN}"
                  echo this is another pipeline trigger step
# workflows: 
#   version: 2
#   run_cdk_dev:
#     jobs:
#       - Job1:
#           filters:
#             branches:
#               only: main
#           context: dev
#           post-step:
#             - run:
#                 command: echo "this is a post step"