name: RunTestsForPR

on:
  push:
    branches: [ main ]

jobs:
  deploy-enabled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: dotenv
        uses: ./.github/actions/dotenv-action
        env:
          path: ".github/workflows/.env"
      - name: Failing GH check to block PR merge
        if: ${{ steps.dotenv.outputs.deploy_enabled == 'false' }}
        run: exit 1
