name: RunTestsForPR

on:
  push:
    branches: [ main ]

jobs:
  deploy-enabled:
    runs-on: ubuntu-latest
    steps:
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
#         with:
#           path: ./.github/workflows/
      - name: Failing GH check to block PR merge
        if: ${{ env.deploy_enabled == 'false' }}
        run: exit 1
