name: RunTestsForPR

on:
  pull_request:
    branches: [ main ]

jobs:
  Run-Flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.10
        run: >
          sudo apt update && sudo apt install python-is-python3 -y
      - name: Setup virtualenv
        run: >
          pip install virtualenv &&
          virtualenv /opt/env/ -ppython3.10
